FROM python:3.12

WORKDIR /app
COPY . .

RUN pip install -r requirements.txt

# Tell gunicorn to bind to $PORT (Render requires this)
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:$PORT"]